################################################################################
# USAGE:
# make init         .... install requirements (via pip)

init:
	python3 -m pip install -r requirements.txt

.PHONY: init
